# Generated by Django 4.2.4 on 2023-08-16 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('body', models.TextField(max_length=800, verbose_name='Body')),
                ('descrption', models.TextField(max_length=255, verbose_name='Description')),
                ('slug', models.SlugField(default='-', verbose_name='Slug')),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='authers.auther', verbose_name='Auther')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('featured_article', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='articles.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.collection', verbose_name='Collection'),
        ),
    ]
