# Generated by Django 4.2.4 on 2023-08-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auther',
            name='email',
            field=models.EmailField(default=1, max_length=255, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auther',
            name='birth_date',
            field=models.DateField(verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='auther',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='auther',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
    ]
