# Generated by Django 4.2.4 on 2023-08-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authers', '0002_auther_email_alter_auther_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auther',
            name='email',
            field=models.EmailField(max_length=256, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='auther',
            name='first_name',
            field=models.CharField(max_length=128, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='auther',
            name='last_name',
            field=models.CharField(max_length=128, verbose_name='Last Name'),
        ),
    ]
