# Generated by Django 4.2.5 on 2023-09-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authers', '0003_alter_auther_email_alter_auther_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auther',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='auther',
            name='last_name',
        ),
        migrations.AddField(
            model_name='auther',
            name='full_name',
            field=models.CharField(default=156, max_length=256, verbose_name='Full Name'),
            preserve_default=False,
        ),
    ]
